### ISSUE TITLE
pkl and npy files

### ISSUE THREAD

**Issue by hongsukchoi** [luyangzhu/NBA-Players#1]
Hi @luyangzhu, thanks for your great work!

I have interest on the skinning model and the spiral convolution used in it.
Especially, I want to implement and test those codes but I can't find necessary files such as 'train_verts.npy'.

Where can I find files loaded in the 33-40 lines of [mesh_utils.py](https://github.com/luyangzhu/NBA-Players/blob/ea41d5e53538895b20fcc13461a5dab8dd44f62b/img_to_mesh/src/utils/mesh_utils.py#L33) ?

Thanks in advance.

**Comment by luyangzhu** [comment]
Thanks for your interest. 

They are in the mesh_release.zip in our [NBA2K dataset](https://github.com/luyangzhu/NBA2K-dataset). You need to download the processed dataset first to make it work. After you unzip it, you should find them under `mesh_release/release/kedrick/${body_part}/preprocessed/` folder.

One more thing to clarify, the train_verts.npy, valid_verts.npy and test_verts.npy are dummy data that are used as the parameters for the [ShapeData](https://github.com/luyangzhu/NBA-Players/blob/ea41d5e53538895b20fcc13461a5dab8dd44f62b/img_to_mesh/src/utils/mesh_utils.py#L33) function. This function is taken from the [original implementation](https://github.com/gbouritsas/Neural3DMM/blob/master/shape_data.py) of Spiral Conv, so I generate these data mainly for compatible reasons. They have nothing to do with the train/valid/test split I use. And that's why I only generate these data for one player.

**Comment by hongsukchoi** [comment]
Thank you for your clarification. Now I am getting light on the codes!

**Comment by hongsukchoi** [comment]
Thank you for your clarification. Now I am getting light on the codes!
